# docker-compose.yml

version: "3"
services:
  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
  nestjs:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  react:
    build:
      context: ./auth-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nestjs
